# Generated by Django 4.2 on 2023-04-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
